name: classlytic_app
description: "A new Flutter project."
publish_to: 'none'

# Version and build number
version: 1.0.0+1

environment:
  sdk: '^3.6.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  mobile_scanner: ^3.2.0
  url_launcher: ^6.1.14
  shared_preferences: ^2.2.3
  camera: ^0.10.5+2
  provider: ^6.0.5
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1 
  firebase_storage: ^12.4.4 
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/Cuboid.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Cuboid.png"
  adaptive_icon_foreground: "assets/Cuboid.png"
  adaptive_icon_background: "#C8C6C6"
